apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capm3-system
resources:
- https://raw.githubusercontent.com/metal3-io/baremetal-operator/master/config/render/capm3.yaml
- secrets.yaml

configMapGenerator:
- behavior: merge
  literals:
  - DEPLOY_KERNEL_URL=${DEPLOY_KERNEL_URL}
  - DEPLOY_RAMDISK_URL=${DEPLOY_RAMDISK_URL}
  - IRONIC_ENDPOINT=${IRONIC_URL}
  - IRONIC_INSPECTOR_ENDPOINT=${IRONIC_INSPECTOR_URL}
  - IRONIC_CACERT_FILE=/opt/metal3/certs/ca/tls.crt
  name: baremetal-operator-ironic
  namespace: baremetal-operator-system


patchesStrategicMerge:
- bmo_image_patch.yaml
- bmo_pull_policy_patch.yaml
- secret_mount_patch.yaml

patchesJson6902:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: baremetal-operator-serving-cert
      namespace: baremetal-operator-system
    path: bmo_patch_cert_dns.yaml
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: baremetal-operator-validating-webhook-configuration
    path: bmo_inject_ca_patch.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: baremetalhosts.metal3.io
    path: bmo_inject_ca_patch.yaml

configurations:
- kustomizeconfig.yaml