apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal3-baremetal-operator
spec:
  template:
    spec:
      containers:
      - name: baremetal-operator
        volumeMounts:
          - name: cacert
            mountPath: "/opt/metal3/${IRONIC_NO_CA_CERT:-certs}/ca/"
            readOnly: true
          - name: ironic-credentials
            mountPath: "/opt/metal3/${IRONIC_NO_BASIC_AUTH:-auth}/ironic"
            readOnly: true
          - name: ironic-inspector-credentials
            mountPath: "/opt/metal3/${IRONIC_INSPECTOR_NO_BASIC_AUTH:-auth}/ironic-inspector"
            readOnly: true
      volumes:
      - name: cacert
        secret:
          secretName: ironic-cacert
      - name: ironic-credentials
        secret:
          secretName: ironic-credentials
      - name: ironic-inspector-credentials
        secret:
          secretName: ironic-inspector-credentials