apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- core-components.yaml
- bootstrap-components.yaml
- ctlplane-components.yaml
- infrastructure-components.yaml
patchesStrategicMerge:
- manager_tolerations_patch.yaml
- image_versions_patch.yaml
