apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ${CLUSTER_NAME}-md-0
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    nodepool: nodepool-0
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
        nodepool: nodepool-0
    spec:
      nodeDrainTimeout: ${NODE_DRAIN_TIMEOUT:-"0s"}
      clusterName: ${CLUSTER_NAME}
      version: ${KUBERNETES_VERSION}
      bootstrap:
        configRef:
          name: ${CLUSTER_NAME}-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: ${CLUSTER_NAME}-md-0
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      image:
        checksum: ${IMAGE_CHECKSUM}
        checksumType: ${IMAGE_CHECKSUM_TYPE}
        format: ${IMAGE_FORMAT}
        url: ${IMAGE_URL}
      dataTemplate:
        name: ${CLUSTER_NAME}-md-metadata
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: ${CLUSTER_NAME}-md-metadata
spec:
  clusterName: ${CLUSTER_NAME}
  metaData:
    strings:
      - key: abc
        value: def
    indexes:
      - key: index_0_1
        offset: 0
        step: 1
      - key: index_3
        offset: 3
      - key: index_5_2
        offset: 5
        step: 2
    objectNames:
      - key: machine_name
        object: machine
      - key: metal3machine_name
        object: metal3machine
      - key: bmh_name
        object: baremetalhost
    ipAddressesFromIPPool:
      - key: ip_1
        name: pool1
      - key: ip_2
        name: pool2
      - key: ip6_1
        name: pool6-1
      - key: ip6_2
        name: pool6-2
    prefixesFromIPPool:
      - key: prefix_1
        name: pool1
      - key: prefix_2
        name: pool2
      - key: prefix6_1
        name: pool6-1
      - key: prefix6_2
        name: pool6-2
    gatewaysFromIPPool:
      - key: gateway_1
        name: pool1
      - key: gateway_2
        name: pool2
      - key: gateway6_1
        name: pool6-1
      - key: gateway6_2
        name: pool6-2
    fromHostInterfaces:
      - key: mac
        interface: eth0
  networkData:
    links:
      ethernets:
        - type: phy
          id: enp1s0
          macAddress:
            fromHostInterface: eth0
        - type: phy
          id: enp2s0
          macAddress:
            fromHostInterface: eth1
    networks:
      ipv4DHCP:
        - id: provisioning
          link: enp1s0
      ipv4:
        - id: baremetal
          link: enp2s0
          ipAddressFromIPPool: pool1
          routes:
            - network: 0.0.0.0
              prefix: 0
              gateway:
                fromIPPool: pool1
              services:
                dns:
                  - 8.8.4.4
    services:
      dns:
        - 8.8.8.8
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.hostname }}'
          kubeletExtraArgs:
            cloud-provider: baremetal
