apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default

labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/v1beta1: v1beta1
    cluster.x-k8s.io/v1beta2: v1beta2

resources:
- bases/infrastructure.cluster.x-k8s.io_metal3clusters.yaml
- bases/infrastructure.cluster.x-k8s.io_metal3clustertemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_metal3machines.yaml
- bases/infrastructure.cluster.x-k8s.io_metal3machinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_metal3datatemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_metal3datas.yaml
- bases/infrastructure.cluster.x-k8s.io_metal3dataclaims.yaml
- bases/infrastructure.cluster.x-k8s.io_metal3remediations.yaml
- bases/infrastructure.cluster.x-k8s.io_metal3remediationtemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_metal3machines.yaml
- path: patches/webhook_in_metal3clusters.yaml
- path: patches/webhook_in_metal3machinetemplates.yaml
- path: patches/webhook_in_metal3datatemplates.yaml
- path: patches/webhook_in_metal3datas.yaml
- path: patches/webhook_in_metal3dataclaims.yaml
- path: patches/webhook_in_metal3remediations.yaml
- path: patches/webhook_in_metal3remediationtemplates.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_metal3machines.yaml
- path: patches/cainjection_in_metal3clusters.yaml
- path: patches/cainjection_in_metal3machinetemplates.yaml
- path: patches/cainjection_in_metal3datatemplates.yaml
- path: patches/cainjection_in_metal3datas.yaml
- path: patches/cainjection_in_metal3dataclaims.yaml
- path: patches/cainjection_in_metal3remediations.yaml
- path: patches/cainjection_in_metal3remediationtemplates.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [ANNOTATION] To add CRD name check skip, uncomment the section with [ANNOTATION] prefix.
# patch here is for adding an annotation for specific CRD (Metal3Data)
- path: patches/skipcrdnamecheck_in_metal3datas.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
