apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam-controller-manager
  namespace: capm3-system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: quay.io/metal3-io/ip-address-manager:v1.1.1
        name: manager