apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# When updating the release, update also the image tag in image_patch.yaml
resources:
- https://github.com/metal3-io/ip-address-manager/releases/download/v1.9.6/ipam-components.yaml

patches:
- path: image_patch.yaml
- path: pull_policy_patch.yaml
