---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.1
  creationTimestamp: null
  name: metal3remediationtemplates.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: Metal3RemediationTemplate
    listKind: Metal3RemediationTemplateList
    plural: metal3remediationtemplates
    shortNames:
    - m3rt
    - m3remediationtemplate
    - m3remediationtemplates
    - metal3rt
    - metal3remediationtemplate
    singular: metal3remediationtemplate
  scope: Namespaced
  versions:
  - name: v1alpha5
    schema:
      openAPIV3Schema:
        description: Metal3RemediationTemplate is the Schema for the metal3remediationtemplates
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Metal3RemediationTemplateSpec defines the desired state of
              Metal3RemediationTemplate.
            properties:
              template:
                description: Metal3RemediationTemplateResource describes the data
                  needed to create a Metal3Remediation from a template.
                properties:
                  spec:
                    description: Spec is the specification of the desired behavior
                      of the Metal3Remediation.
                    properties:
                      strategy:
                        description: Strategy field defines remediation strategy.
                        properties:
                          retryLimit:
                            description: Sets maximum number of remediation retries.
                            type: integer
                          timeout:
                            description: Sets the timeout between remediation retries.
                            type: string
                          type:
                            description: Type of remediation.
                            type: string
                        type: object
                    type: object
                required:
                - spec
                type: object
            required:
            - template
            type: object
          status:
            description: Metal3RemediationTemplateStatus defines the observed state
              of Metal3RemediationTemplate.
            properties:
              status:
                description: Metal3RemediationStatus defines the observed state of
                  Metal3Remediation
                properties:
                  lastRemediated:
                    description: LastRemediated identifies when the host was last
                      remediated
                    format: date-time
                    type: string
                  phase:
                    description: Phase represents the current phase of machine remediation.
                      E.g. Pending, Running, Done etc.
                    type: string
                  retryCount:
                    description: RetryCount can be used as a counter during the remediation.
                      Field can hold number of reboots etc.
                    type: integer
                type: object
            required:
            - status
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Metal3RemediationTemplate is the Schema for the metal3remediationtemplates
          API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Metal3RemediationTemplateSpec defines the desired state of
              Metal3RemediationTemplate.
            properties:
              template:
                description: Metal3RemediationTemplateResource describes the data
                  needed to create a Metal3Remediation from a template.
                properties:
                  spec:
                    description: Spec is the specification of the desired behavior
                      of the Metal3Remediation.
                    properties:
                      strategy:
                        description: Strategy field defines remediation strategy.
                        properties:
                          retryLimit:
                            description: Sets maximum number of remediation retries.
                            type: integer
                          timeout:
                            description: Sets the timeout between remediation retries.
                            type: string
                          type:
                            description: Type of remediation.
                            type: string
                        type: object
                    type: object
                required:
                - spec
                type: object
            required:
            - template
            type: object
          status:
            description: Metal3RemediationTemplateStatus defines the observed state
              of Metal3RemediationTemplate.
            properties:
              status:
                description: Metal3RemediationStatus defines the observed state of
                  Metal3Remediation
                properties:
                  lastRemediated:
                    description: LastRemediated identifies when the host was last
                      remediated
                    format: date-time
                    type: string
                  phase:
                    description: Phase represents the current phase of machine remediation.
                      E.g. Pending, Running, Done etc.
                    type: string
                  retryCount:
                    description: RetryCount can be used as a counter during the remediation.
                      Field can hold number of reboots etc.
                    type: integer
                type: object
            required:
            - status
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
