name: Validate SECURITY_INSIGHTS.yml
on:
  pull_request:
    paths:
    - SECURITY_INSIGHTS.yml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Install CUE
      uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1

    - name: Fetch Security Insights schema
      run: |
        mkdir -p /tmp/si-spec
        curl -sSfL -o /tmp/si-spec/schema.cue \
          https://raw.githubusercontent.com/ossf/security-insights/v2.2.0/spec/schema.cue

    - name: Validate schema
      run: cue vet -d '#SecurityInsights' /tmp/si-spec/schema.cue SECURITY_INSIGHTS.yml
